/**
 * SEED_EVENTS
 * Known recurring HKIA seasonal events with approximate annual date ranges.
 * Dates are stored as { month (1-12), day } objects so they work year-over-year.
 * "type" is one of: primary | secondary | calendar | flash
 * Dates sourced from wiki + community guides — may shift slightly each year.
 */

export const EVENT_TYPES = {
  primary:   { label: "Primary",   color: "#e8003c", bg: "#fff0f3" },
  secondary: { label: "Secondary", color: "#7c3aed", bg: "#f5f0ff" },
  calendar:  { label: "Calendar",  color: "#0369a1", bg: "#f0f9ff" },
  flash:     { label: "Flash",     color: "#b45309", bg: "#fffbeb" },
};

export const SEED_EVENTS = [
  {
    id: "frosty-fashion-frenzy",
    name: "Frosty Fashion Frenzy",
    emoji: "❄️",
    type: "calendar",
    startMonth: 1, startDay: 12,
    endMonth: 1,   endDay: 25,
    description: "Log in daily for wintery fashion rewards from a gift calendar.",
    notes: "Dates shift slightly each year.",
  },
  {
    id: "luck-and-lanterns",
    name: "Luck and Lanterns Celebration",
    emoji: "🏮",
    type: "primary",
    startMonth: 1, startDay: 18,
    endMonth: 2,   endDay: 28,
    description: "Lunar New Year-inspired event. Collect lantern currency around the Seaside Resort for themed furniture and clothing.",
    notes: "One of the longer primary events — spans ~6 weeks.",
  },
  {
    id: "hugs-and-hearts",
    name: "Hugs and Hearts",
    emoji: "💝",
    type: "secondary",
    startMonth: 2, startDay: 8,
    endMonth: 2,   endDay: 22,
    description: "Valentine's Day celebration. Capture Lovebugs and place them in habitats to earn heart-themed rewards.",
    notes: "Typically starts around Feb 8th.",
  },
  {
    id: "springtime-celebration",
    name: "Springtime Celebration",
    emoji: "🌸",
    type: "primary",
    startMonth: 3, startDay: 1,
    endMonth: 4,   endDay: 14,
    description: "Spring has arrived on the island! Collect floral currency for pastel furniture and outfits.",
    notes: "Runs ~6 weeks from early March.",
  },
  {
    id: "happy-haven-days",
    name: "Happy Haven Days",
    emoji: "🏡",
    type: "flash",
    startMonth: 3, startDay: 18,
    endMonth: 3,   endDay: 21,
    description: "A short flash event. Only a few days — don't miss it!",
    notes: "The only flash-type event. Blink and you'll miss it.",
  },
  {
    id: "colorblaze-carnival",
    name: "Colorblaze Carnival",
    emoji: "🎨",
    type: "secondary",
    startMonth: 3, startDay: 25,
    endMonth: 4,   endDay: 14,
    description: "Colourful carnival-themed event overlapping with the Springtime Celebration.",
    notes: "Runs alongside Springtime Celebration.",
  },
  {
    id: "imagination-celebration",
    name: "Imagination Celebration",
    emoji: "🌈",
    type: "primary",
    startMonth: 4, startDay: 15,
    endMonth: 5,   endDay: 31,
    description: "A creative, whimsical event celebrating imagination and play.",
    notes: "Runs ~6 weeks through April–May.",
  },
  {
    id: "month-of-meh",
    name: "Month of Meh",
    emoji: "😑",
    type: "secondary",
    startMonth: 5, startDay: 1,
    endMonth: 5,   endDay: 31,
    description: "Badtz-Maru's signature grumpy event — runs all of May alongside Imagination Celebration.",
    notes: "Runs the entire month of May.",
  },
  {
    id: "under-the-sea",
    name: "Under the Sea Celebration",
    emoji: "🐠",
    type: "primary",
    startMonth: 5, startDay: 28,
    endMonth: 7,   endDay: 9,
    description: "Dive into an ocean-themed event with aquatic furniture and sea creature collecting.",
    notes: "One of the longest events — runs ~6 weeks.",
  },
  {
    id: "paper-parade",
    name: "Paper Parade",
    emoji: "📄",
    type: "secondary",
    startMonth: 6, startDay: 15,
    endMonth: 7,   endDay: 1,
    description: "Origami and paper-craft themed secondary event.",
    notes: "Runs mid-June to July 1st.",
  },
  {
    id: "sunshine-celebration",
    name: "Sunshine Celebration",
    emoji: "☀️",
    type: "primary",
    startMonth: 7, startDay: 1,
    endMonth: 8,   endDay: 15,
    description: "Summer is here! Collect sunshine currency for bright, summery rewards.",
    notes: "In 2023 this ran late Aug–Sep; now settled in July.",
  },
  {
    id: "friendship-festival",
    name: "Friendship Festival",
    emoji: "🤝",
    type: "secondary",
    startMonth: 7, startDay: 25,
    endMonth: 8,   endDay: 7,
    description: "Celebrate friendship with the island residents. Short secondary event.",
    notes: "Runs end of July to early August.",
  },
  {
    id: "scholastic-celebration",
    name: "Scholastic Celebration",
    emoji: "🎒",
    type: "primary",
    startMonth: 8, startDay: 24,
    endMonth: 9,   endDay: 18,
    description: "Back to school! Pochacco and Tuxedosam host sporty and school-themed activities.",
    notes: "Kicks off late August.",
  },
  {
    id: "jam-jamboree",
    name: "Jam Jamboree",
    emoji: "🎵",
    type: "secondary",
    startMonth: 9, startDay: 10,
    endMonth: 9,   endDay: 23,
    description: "Musical mini-games, sweet surprises, and sugary decor rewards.",
    notes: "Runs ~2 weeks in mid-September.",
  },
  {
    id: "spooky-celebration",
    name: "Spooky Celebration",
    emoji: "🕷️",
    type: "primary",
    startMonth: 9, startDay: 26,
    endMonth: 11,  endDay: 5,
    description: "The Halloween event! Spooky decorations, costumes, and eerie island activities.",
    notes: "One of the most popular events — runs ~6 weeks.",
  },
  {
    id: "fall-fashion-frenzy",
    name: "Fall Fashion Frenzy",
    emoji: "🍂",
    type: "calendar",
    startMonth: 10, startDay: 1,
    endMonth: 10,   endDay: 14,
    description: "Log in daily for autumnal fashion rewards from a calendar.",
    notes: "First two weeks of October.",
  },
  {
    id: "days-of-plenty",
    name: "Days of Plenty",
    emoji: "🍁",
    type: "secondary",
    startMonth: 11, startDay: 14,
    endMonth: 11,   endDay: 30,
    description: "An autumn harvest celebration. Jump into giant leaf piles and gather event currency for cosy fall rewards.",
    notes: "Second half of November.",
  },
  {
    id: "give-and-gather",
    name: "Give and Gather Celebration",
    emoji: "🎁",
    type: "primary",
    startMonth: 11, startDay: 28,
    endMonth: 12,   endDay: 31,
    description: "The festive holiday event! Gather gifts and celebrate the season with all the island residents.",
    notes: "Runs end of November through all of December.",
  },
  {
    id: "lighttime-jubilee",
    name: "Lighttime Jubilee",
    emoji: "✨",
    type: "secondary",
    startMonth: 12, startDay: 15,
    endMonth: 1,    endDay: 15,
    description: "A sparkling New Year celebration spanning December into January.",
    notes: "Wraps around New Year — endDay is in the following January.",
  },
];
