export const STATIONS = [
  {
    id: "oven",
    name: "Oven",
    emoji: "🍞",
    type: "create",
    availability: "immediate",
    owners: ["Hello Kitty"],
    baseIngredient: "Flour",
    baseSlots: 2,
    upgrade: { friendshipLevel: 15, slots: 3 },
    dlc: null,
  },
  {
    id: "cauldron",
    name: "Cauldron",
    emoji: "🧪",
    type: "create",
    availability: "quest",
    owners: ["Kuromi"],
    location: "Witch's Hut, Spooky Swamp",
    baseIngredient: "Glow Berry",
    baseSlots: 2,
    unlockCondition: { friendshipLevel: 8, resident: "Kuromi", quest: "Potion Hunt: The Opening" },
    upgrade: {
      type: "quest",
      quest: "Potion Solutions",
      friendshipLevel: 16,
      resident: "Cogimyun",
      slots: 3,
      fixedIngredient: "Stained Glass",
      dlc: "Wheatflour Wonderland",
    },
    dlc: null,
  },
  {
    id: "soda_machine",
    name: "Soda Machine",
    emoji: "🥤",
    type: "create",
    availability: "quest",
    owners: ["Pekkle"],
    location: "Gemstone Town",
    baseIngredient: "Fizzy Crystal",
    baseSlots: 2,
    unlockCondition: {
      quest: "Parched",
      prerequisites: ["Dessert-ed Boat", "Open the Nature Preserve", "Meet the Island Beings"],
    },
    upgrade: { friendshipLevel: 6, resident: "Pekkle", slots: 3 },
    dlc: null,
  },
  {
    id: "dessert_machine",
    name: "Dessert Machine",
    emoji: "🍨",
    type: "create",
    availability: "quest",
    owners: ["Pompompurin"],
    location: "Dessert Boat, Gemstone Mountain",
    baseIngredient: "Cactus Cream",
    baseSlots: 2,
    unlockCondition: {
      quest: "Dessert-ed Boat",
      prerequisites: [
        { quest: "Power Up the Gate", friendshipLevel: 1, resident: "Chococat" },
        { friendshipLevel: 4, resident: "Pompompurin" },
      ],
    },
    upgrade: { friendshipLevel: 13, resident: "Pompompurin", slots: 3 },
    dlc: null,
  },
  {
    id: "egg_pan",
    name: "Egg Pan Station",
    emoji: "🍳",
    type: "create",
    availability: "quest",
    owners: ["Pekkle", "Pompompurin"],
    location: "Gemstone Mountain",
    baseIngredient: "Egg",
    baseSlots: 2,
    unlockCondition: {
      quest: "An Egg-cellent Pan",
      prerequisites: [
        { quest: "Rockadoodler Roundup", friendshipLevel: 8, resident: "Pekkle", prerequisiteQuest: "Open the Nature Preserve" },
      ],
    },
    upgrade: { type: "collection", goal: 102, collectible: "Gudetama photos", claimFrom: "Pochacco", claimLocation: "Gudetama Sign", slots: 3 },
    dlc: null,
  },
  {
    id: "pizza_oven",
    name: "Pizza Oven",
    emoji: "🍕",
    type: "create",
    availability: "immediate",
    owners: ["Retsuko"],
    location: "Mount Hothead",
    baseIngredient: "Dough",
    baseSlots: 2,
    upgrade: { friendshipLevel: 9, resident: "Retsuko", slots: 3 },
    dlc: null,
    note: "Located at Mount Hothead — technically available from the start but very difficult to reach without Stamina upgrades or the Spooky Swamp zip line unlocked.",
  },
  {
    id: "espresso_comedy",
    name: "Espresso Machine",
    emoji: "☕",
    type: "create",
    availability: "quest",
    owners: ["Hangyodon"],
    location: "Comedy Club",
    baseIngredient: "Candlenut",
    baseSlots: 2,
    unlockCondition: {
      note: "Accessible upon reaching the Comedy Club via the Snorkel",
      requires: "Snorkel",
      snorkelQuest: {
        quest: "Deep Diving",
        prerequisites: [
          { friendshipLevel: 6, resident: "Kuromi" },
          { quest: "Finding Flippers", friendshipLevel: 1, resident: "Keroppi", prerequisiteQuest: "Power Up the Gate" },
          { quest: "Re-Haunt the Spooky Swamp", friendshipLevel: 4, resident: "Kuromi", prerequisiteQuest: "Power Up the Gate" },
        ],
      },
    },
    upgrade: { friendshipLevel: 4, resident: "Hangyodon", slots: 3 },
    dlc: null,
    note: "May require extra Stamina to reach the Comedy Club.",
  },
  {
    id: "espresso_cafe",
    name: "Espresso Machine",
    emoji: "☕",
    type: "create",
    availability: "quest",
    owners: ["Hello Kitty"],
    location: "Hello Kitty Cafe",
    baseIngredient: "Candlenut",
    baseSlots: 2,
    unlockCondition: {
      quest: "Espresso Machine Repair",
      friendshipLevel: 11,
      resident: "Hangyodon",
    },
    upgrade: { friendshipLevel: 4, resident: "Hangyodon", slots: 3 },
    dlc: null,
  },
];

export const STATION_MAP = Object.fromEntries(STATIONS.map((s) => [s.id, s]));